Class {
	#name : 'VMMethodCacheConstants',
	#superclass : 'SharedPool',
	#classVars : [
		'LookupRuleDynamicSuper',
		'LookupRuleImplicit',
		'LookupRuleMNU',
		'LookupRuleOrdinary',
		'LookupRuleSelf',
		'MethodCacheClass',
		'MethodCacheEntries',
		'MethodCacheEntrySize',
		'MethodCacheMask',
		'MethodCacheMethod',
		'MethodCachePrim',
		'MethodCachePrimFunction',
		'MethodCacheSelector',
		'MethodCacheSize'
	],
	#category : 'VMMaker-Interpreter',
	#package : 'VMMaker',
	#tag : 'Interpreter'
}
