Class {
	#name : 'VMStackFrameOffsets',
	#superclass : 'SharedPool',
	#classVars : [
		'FoxCallerSavedIP',
		'FoxIFReceiver',
		'FoxIFSavedIP',
		'FoxIFrameFlags',
		'FoxMFReceiver',
		'FoxMethod',
		'FoxSavedFP',
		'FoxThisContext',
		'FrameSlots',
		'IFrameSlots',
		'MFMethodFlagHasContextFlag',
		'MFMethodFlagIsBlockFlag',
		'MFMethodFlagsMask',
		'MFMethodMask',
		'MFrameSlots'
	],
	#category : 'VMMaker-Interpreter',
	#package : 'VMMaker',
	#tag : 'Interpreter'
}
